### ISSUE TITLE
fileHeader rule: discrepancies between local development environments and GitHub Actions CI.

### ISSUE THREAD

**Issue by swiftanon** [nicklockwood/SwiftFormat#1840]
### Issue Summary

The `--header` formatting rule in `.swiftformat` is causing discrepancies between local development environments and GitHub Actions CI. Files that pass formatting checks locally fail in CI, specifically due to header formatting.

### Steps to Reproduce

1. Set up a Swift project with the following `.swiftformat` configuration:
    ```yaml
    --header "{file}\nCreated by {author.name} on {created}."
    --indent 4
    --indentcase true
    --ifdef outdent
    ```
2. Run `swiftformat .` locally to format files.
3. Add a github actions workflow for a formatting; using the below as an example:
```yaml
# .github/workflows/Lint.yml
name: Lint

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0        

      - name: Set up Swift
        uses: SwiftyLab/setup-swift@v1
        with:
          swift-version: '5.9.2'

      - name: Debug Environment Differences
        run: |
          echo "Swift version:"
          swift --version
          echo "SwiftFormat version:"
          swiftformat --version
          echo "Current working directory:"
          pwd
          echo "Environment variables:"
          env
          echo "SwiftFormat configuration:"
          cat .swiftformat

      - name: Fail if files need formatting
        run: |
          set -e
          swiftformat --lint . | grep -q "file needs formatting" && (echo "Files need formatting. Please run 'swiftformat .' locally."; exit 1)
```
4. Push the code to a GitHub repository
5. Observe that CI fails due to formatting issues, specifically with headers.

### **Expected Behavior**

The same formatting results between local and CI environments, with no discrepancies in the header formatting.

### **Actual Behavior**

CI reports formatting issues related to headers, even though locally formatted files do not exhibit these issues.

### **Environment Details**

- **Swift Version**: 5.9.2
- **SwiftFormat Version**: 0.54.3
- **CI Environment**: GitHub Actions, macOS 14.0
- **Local Environment**: macOS 14.0 (arm64)

### **`.swiftformat` Configuration File**

```yaml
--header "{file}\nCreated by {author.name} on {created}."
--indent 4
--indentcase true
--ifdef outdent
